---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      when:  ansible_os_family=="Debian"
    - name: Install nginx on redhat family
      package:
        name: httpd
        state: present
      when: ansible_os_family=="RedHat"
    - name: Start httpd daemon
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family=="RedHat"
    - name: Create user Ricardo
      user:
        name: Ricardo
        comment: Ricardo Sanon
        shell: /bin/bash
    - name: create group
      group:
        name: cloudteam
        state: present
    - name: create index file
      file:
        path: /var/www/html/index.html
        state: touch
    - name: Create directory
      file:
        path: /tmp/os
        state: directory

    - name: copy content t index
      copy:
        dest: /var/www/html/index.html
        content: This is created using ansible
  